### PR TITLE
Add Hibernate 5.3.11 compile profile

### PR DESCRIPTION
**Pull request by kristianvld**
Adding a maven profile option to compile with Hibernate 5.3.11, example:

`mvn clean package -DskipTests -Dhibernate5.3.11`

Exploiting hibernate 5 works just as before:

`java -Dhibernate5 -jar target/ysoserial-0.0.6-SNAPSHOT-all.jar Hibernate1 "touch /tmp/ysoserial"`

### CODE REVIEW

**Comment by frohoff** [comment]
Sorry for taking so long to reply to this. Can you be more specific about what compilation error is this fixing?
